---
- name: Launch EC2 Instance
  hosts: localhost
  tasks:
    - name: Launch EC2 instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ aws_region }}"
        group: "{{ ec2_security_group_name }}"
        wait: yes
        count: 1
        instance_tags:
          Name: WebServer
      register: ec2_instance

    - name: Add newly created EC2 instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2_instance.instances }}"

    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 60
        timeout: 300
        host: "{{ item.public_ip }}"
      loop: "{{ ec2_instance.instances }}"